/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "attachx.c"
#include "cfacts.c"
#include "dragcfact.c"
#include "fakefullscreenclient.c"
#include "floatpos.c"
#include "fullscreen.c"
#include "moveresize.c"
#include "pertag.c"
#include "placemouse.c"
#include "scratchpad.c"
#include "scratchpad_alt_1.c"
#include "stacker.c"
#include "tagswapmon.c"
#include "vanitygaps.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_flextile-deluxe.c"
#include "layout_monocle.c"
#include "layout_tile.c"

